### ISSUE TITLE
.modlist

### ISSUE THREAD

**Issue by dubux** [veiset/Brunobot#13]
Usage of .modlist displays **init** which should be ignored. Without looking at the code I'm making an assumption that the current method of recognizing modules via .modlist is buy listing all files or ".py" files in the /extras directory. I would recommend a function which reads each module first checking for a she-bang line as well as verifying that all required variables for bruno are set within the file. Files like **init** would not contain these items and thus not be recognized as a bruno loadable module.

**Comment by veiset** [comment]
It would be impractical to verify all the extra modules before trying to actually load them, as this could possibly cause the bot to do a lot more work than what is sensible. Imagine having to check ~15-20 extra modules each time the bot is asked to list the modules that can currently be loaded.
